# Generated by Django 4.2.9 on 2024-02-12 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('M', '男'), ('F', '女')], max_length=1)),
                ('address', models.CharField(max_length=200)),
                ('temperature', models.FloatField()),
            ],
        ),
    ]
