# Generated by Django 4.2.9 on 2024-02-23 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(max_length=6, unique=True)),
                ('name', models.CharField(max_length=12)),
                ('author', models.CharField(max_length=16)),
                ('date', models.CharField(max_length=24)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=32, unique=True)),
                ('password', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=32)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=4)),
                ('career', models.CharField(max_length=18)),
                ('date', models.CharField(max_length=24)),
            ],
        ),
        migrations.CreateModel(
            name='LendBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lend_date', models.CharField(max_length=24)),
                ('book_num', models.ForeignKey(db_column='book_num', on_delete=django.db.models.deletion.CASCADE, to='WEBAPI.book', to_field='num')),
                ('user_account', models.ForeignKey(db_column='user_account', on_delete=django.db.models.deletion.CASCADE, to='WEBAPI.userinfo', to_field='account')),
            ],
        ),
    ]
