# Generated by Django 4.2.9 on 2024-04-17 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmos', '0004_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_borrowed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('bookdata', models.CharField(max_length=200)),
            ],
        ),
    ]
