# Generated by Django 4.2.9 on 2024-06-01 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmos', '0005_user_borrowed'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_borrowed',
            name='borrow_bid',
            field=models.CharField(default='0', max_length=8),
        ),
        migrations.AddField(
            model_name='user_borrowed',
            name='userright',
            field=models.CharField(default='A', max_length=1),
        ),
    ]
