# Generated by Django 4.2.9 on 2024-06-01 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hmos', '0006_user_borrowed_borrow_bid_user_borrowed_userright'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_borrowed',
            old_name='bookdata',
            new_name='password',
        ),
    ]
